version: 0.0
os: linux
files:
  - source: /
    destination: /home/mahesh/Desktop/ansible-running-codedeploy/copy-files
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
